### PR TITLE
Use `io.open_code` for reading code

### PR DESCRIPTION
**Pull request by johnslavik**

### CODE REVIEW

**Comment by johnslavik** [comment]
Let me know if you prefer a version with the import inlined, `__import__('io').open_code()`.

**Comment by jaraco** [comment]
Looks good. Can you explain briefly what motivated this change? I read the docs for `open_code` and it says the behavior is the same (for an absolute path).

**Comment by johnslavik** [comment]
I mistakenly claimed that it's a recommended solution.
It's not.

So the only value I can see in this PR is very relative to what are our values:
- it can be educative, as the `io.open_code` function isn't popular
- it can be less readable, as the `io.open_code` function isn't popular

I leave the decision up to you (not like I have to--the decision was already yours ever since).

A decision that has not much of a meaning to the outcome of the code... I think.
But running into `io.open_code`, and then discussing this PR with my friends, helped me find myself again.

Oh gosh do I love computer science.

**Comment by jaraco** [comment]
Okay. I normally would say not to changes that have little impact. In this case, because `open_code` implies `mode='rb'`, I like it better. Let's merge it.

**Pull request merged**
